version: 2
jobs:
  tests:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Get our data and merge with upstream
      - run: sudo apt-get update
      - checkout

      - restore_cache:
          keys:
            - cache-pip

      - run: pip install --user .[testing,pdfhtml]
      - save_cache:
          key: cache-pip
          paths:
            - ~/.cache/pip

      - run:
          name: Install Headless Chrome dependencies
          command: |
            sudo apt-get install -yq $(cat .github/workflows/pyppeteer_reqs.txt)

      - run:
          name: Install chromium
          command: pyppeteer-install

      # Make sure tests build in CircleCI (so we can preview w/ SSH if we wish)
      - run:
          name: Run pytest
          command: pytest

      # Build a PDF of the book to view as an artifact
      - run:
          name: PDF from HTML
          command: jb build docs --build pdfhtml

      - store_artifacts:
          path: docs/_build/pdf/book.pdf
          destination: pdf
workflows:
  version: 2
  default:
    jobs:
      - tests
